/*!
 * squeegee 1.0 - http://jameskeane.github.com/squeege
 */
(function(window,document,Math,undefined){if(!window.Squeegee){window.Squeegee={};}
var Squeegee=window.Squeegee;(function(){if(Squeegee.Config){return;}
Squeegee.Config={debugMode:false,animationTime:1.5,logarithmicZoom:true,springStiffness:5.0,zoomPerClick:2.0,zoomPerScroll:Math.pow(2,1/3),zoomPerSecond:2.0};})();Squeegee.Spring=function(initialValue){var currentValue=typeof(initialValue)=="number"?initialValue:0;var startValue=currentValue;var targetValue=currentValue;var currentTime=new Date().getTime();var startTime=currentTime;var targetTime=currentTime;function transform(x){var s=Squeegee.Config.springStiffness;return(1.0-Math.exp(-x*s))/(1.0-Math.exp(-s));}
this.getCurrent=function(){return currentValue;};this.getTarget=function(){return targetValue;};this.resetTo=function(target){targetValue=target;targetTime=currentTime;startValue=targetValue;startTime=targetTime;};this.springTo=function(target){startValue=currentValue;startTime=currentTime;targetValue=target;targetTime=startTime+1000*Squeegee.Config.animationTime;};this.shiftBy=function(delta){startValue+=delta;targetValue+=delta;};this.update=function(){currentTime=new Date().getTime();currentValue=(currentTime>=targetTime)?targetValue:startValue+(targetValue-startValue)*transform((currentTime-startTime)/(targetTime-startTime));};};Squeegee.Utils=new(function(){var self=this;(function(){})();this.getElement=function(elmt){if(typeof(elmt)=="string"){elmt=document.getElementById(elmt);}
return elmt;};this.getEvent=function(event){return event?event:window.event;};this.getEventPoint=function(evt){var p=document.documentElement.createSVGPoint();p.x=evt.clientX;p.y=evt.clientY;return p;};this.setCTM=function(elmt,matrix){var s="matrix("+matrix.a+","+matrix.b+","+matrix.c+","+matrix.d+","+matrix.e+","+matrix.f+")";elmt.setAttribute("transform",s);};this.dumpMatrix=function(matrix){var s="[ "+matrix.a+", "+matrix.c+", "+matrix.e+"\n  "+matrix.b+", "+matrix.d+", "+matrix.f+"\n  0, 0, 1 ]";return s;};this.setAttributes=function(elmt,attributes){for(i in attributes)
elmt.setAttributeNS(null,i,attributes[i]);};this.getMouseScroll=function(event){var event=self.getEvent(event);var delta=0;if(typeof(event.wheelDelta)=="number"){delta=event.wheelDelta;}else if(typeof(event.detail)=="number"){delta=event.detail*-1;}else{}
return delta?delta/Math.abs(delta):0;};this.addEvent=function(elmt,eventName,handler,useCapture){var elmt=self.getElement(elmt);if(elmt.addEventListener){if(eventName=="mousewheel"){elmt.addEventListener("DOMMouseScroll",handler,useCapture);}
elmt.addEventListener(eventName,handler,useCapture);}else if(elmt.attachEvent){elmt.attachEvent("on"+eventName,handler);if(useCapture&&elmt.setCapture){elmt.setCapture();}}else{}};this.removeEvent=function(elmt,eventName,handler,useCapture){var elmt=self.getElement(elmt);if(elmt.removeEventListener){if(eventName=="mousewheel"){elmt.removeEventListener("DOMMouseScroll",handler,useCapture);}
elmt.removeEventListener(eventName,handler,useCapture);}else if(elmt.detachEvent){elmt.detachEvent("on"+eventName,handler);if(useCapture&&elmt.releaseCapture){elmt.releaseCapture();}}else{}};this.cancelEvent=function(event){var event=self.getEvent(event);if(event.preventDefault){event.preventDefault();}
event.cancel=true;event.returnValue=false;};this.stopEvent=function(event){var event=self.getEvent(event);if(event.stopPropagation){event.stopPropagation();}
event.cancelBubble=true;};});Squeegee.Viewer=function(container){var self=this;var parent=Squeegee.Utils.getElement(container);var root=document.documentElement;var panning=false;var zooming=false;var animating=false;var stateTarget,stateOrigin;stateTf=parent.getCTM().inverse();var centerSpringX=new Squeegee.Spring(0);var centerSpringY=new Squeegee.Spring(0);var zoomSpring=new Squeegee.Spring(Squeegee.Config.logarithmicZoom?0:1);var zoomPoint;var LN2=Math.LN2;function initialize(){Squeegee.Utils.addEvent(root,'mouseup',onMouseUp,false);Squeegee.Utils.addEvent(root,'mousedown',onMouseDown,false);Squeegee.Utils.addEvent(root,'mousemove',onMouseMove,false);Squeegee.Utils.addEvent(root,'mousewheel',onMouseScroll,false);update();}
function log2(x){return Math.log(x)/LN2;}
function pow2(x){return Math.pow(2,x);}
function getZoom(current){var zoom;if(current){zoom=zoomSpring.getCurrent();return Squeegee.Config.logarithmicZoom?pow2(zoom):zoom;}else{zoom=zoomSpring.getTarget();return Squeegee.Config.logarithmicZoom?pow2(zoom):zoom;}};function scheduleUpdate(updateFunc,prevUpdateTime){if(animating){return window.setTimeout(updateFunc,1);}
var currentTime=new Date().getTime();var prevUpdateTime=prevUpdateTime?prevUpdateTime:currentTime;var targetTime=prevUpdateTime+1000/60;var deltaTime=Math.max(1,targetTime-currentTime);return window.setTimeout(updateFunc,deltaTime);}
function update(){var beginTime=new Date().getTime();var oldZoom=zoomSpring.getCurrent();var oldCenterX=centerSpringX.getCurrent(),oldCenterY=centerSpringY.getCurrent();zoomSpring.update();if(zoomSpring.getCurrent()!=oldZoom){var p=zoomPoint.matrixTransform(parent.getCTM().inverse());var change=zoomSpring.getCurrent()-oldZoom;var z=1+change;var k=root.createSVGMatrix().translate(p.x,p.y).scale(z).translate(-p.x,-p.y);Squeegee.Utils.setCTM(parent,parent.getCTM().multiply(k));stateTf=stateTf.multiply(k.inverse());}
centerSpringX.update();centerSpringY.update();if(centerSpringX.getCurrent()!=oldCenterX|centerSpringY.getCurrent()!=oldCenterY){Squeegee.Utils.setCTM(parent,stateTf.inverse().translate(centerSpringX.getCurrent(),centerSpringY.getCurrent()));}
if(zoomSpring.getCurrent()==oldZoom&centerSpringX.getCurrent()==oldCenterX&centerSpringY.getCurrent()==oldCenterY)
animating=false;scheduleUpdate(arguments.callee,beginTime);}
function zoomBy(factor,refPoint,immediately){zoomTo(getZoom()*factor,refPoint,immediately);}
function zoomTo(zoom,refPoint,immediately){animating=true;if(immediately){zoomSpring.resetTo(Squeegee.Config.logarithmicZoom?log2(zoom):zoom);}else{zoomSpring.springTo(Squeegee.Config.logarithmicZoom?log2(zoom):zoom);}
zoomPoint=refPoint;}
function onMouseUp(evt){panning=false;}
function onMouseDown(evt){if(!panning){stateTf=parent.getCTM().inverse();stateOrigin=Squeegee.Utils.getEventPoint(evt).matrixTransform(stateTf);centerSpringX.resetTo(0);centerSpringY.resetTo(0);}
panning=true;animating=true;}
function onMouseMove(evt){if(panning==true){var p=Squeegee.Utils.getEventPoint(evt).matrixTransform(stateTf);centerSpringX.springTo(p.x-stateOrigin.x);centerSpringY.springTo(p.y-stateOrigin.y);}}
function onMouseScroll(evt){var delta=Squeegee.Utils.getMouseScroll(evt);var p=Squeegee.Utils.getEventPoint(evt);var factor=Math.pow(Squeegee.Config.zoomPerScroll,delta);zoomBy(factor,p,false);Squeegee.Utils.cancelEvent(evt);}
initialize();};func=function(){(new Squeegee.Viewer(Squeegee.Utils.getElement('viewport')));};if(window.addEventListener)
window.addEventListener('load',func,false);else if(elem.attachEvent)
window.attachEvent('onload',func);})(window,document,Math);